site_name: Zoltar Documentation
repo_url: https://zoltardata.com/
repo_name: Zoltar Main Site
theme: material
markdown_extensions:
  - toc:
      permalink: true

nav:
  - Home: 'index.md'
  - Web Tour:
      - 'Introduction': 'WebTourIntro.md'
      - 'Zoltar Home page': 'HomePage.md'
      - 'Project detail page': 'ProjectDetailPage.md'
      - 'Model detail page': 'ModelDetailPage.md'
      - 'Forecast detail page': 'ForecastDetailPage.md'
  - User Guide:
      - 'Introduction': 'UserIntro.md'
      - 'Projects': 'Projects.md'
      - 'Models': 'Models.md'
      - 'Forecasts': 'Forecasts.md'
      - 'Scores': 'Scoring.md'
      - 'Truth': 'Truth.md'
      - 'Jobs': 'Jobs.md'
      - 'Accounts': 'Accounts.md'
  - Reference:
      - 'Concepts': 'Concepts.md'
      - 'Data model': 'DataModel.md'
      - 'File Formats': 'FileFormats.md'
      - 'Forecast Query Format': 'ForecastQueryFormat.md'
      - 'Score Query Format': 'ScoreQueryFormat.md'
      - 'Targets': 'Targets.md'
      - 'Validation': 'Validation.md'
  - Programming libraries and API:
      - 'Introduction': 'ApiIntro.md'
      - 'zoltpy (Python)': 'Zoltpy.md'
      - 'zoltr (R)': 'Zoltr.md'
      - 'RESTful API': 'Api.md'
  - Getting Help: 'Help.md'
