site_name: Zoltar Documentation
repo_url: https://zoltardata.com/
repo_name: Zoltar Main Site
theme: material
markdown_extensions:
  - toc:
      permalink: true

nav:
  - Home: 'index.md'
  - Web Tour:
      - 'Introduction': 'WebTourIntro.md'
      - 'Zoltar Home page': 'HomePage.md'
      - 'Project detail page': 'ProjectDetailPage.md'
      - 'Project explorer page': 'ProjectExplorerPage.md'
      - 'Forecasts summary page': 'ForecastsSummaryPage.md'
      - 'Forecasts visualization page': 'ForecastsVisualizationPage.md'
      - 'Visualization options page': 'VisualizationOptionsPage.md'
      - 'Model detail page': 'ModelDetailPage.md'
      - 'Forecast detail page': 'ForecastDetailPage.md'
  - User Guide:
      - 'Introduction': 'UserIntro.md'
      - 'Projects': 'Projects.md'
      - 'Models': 'Models.md'
      - 'Forecasts': 'Forecasts.md'
      - 'Truth': 'Truth.md'
      - 'Jobs': 'Jobs.md'
      - 'Accounts': 'Accounts.md'
  - Reference:
      - 'Concepts': 'Concepts.md'
      - 'Data model': 'DataModel.md'
      - 'File Formats': 'FileFormats.md'
      - 'Forecast Query Format': 'ForecastQueryFormat.md'
      - 'Forecast Versions': 'ForecastVersions.md'
      - 'Truth Query Format': 'TruthQueryFormat.md'
      - 'Targets': 'Targets.md'
      - 'Validation': 'Validation.md'
  - Programming libraries and API:
      - 'Introduction': 'ApiIntro.md'
      - 'zoltpy (Python)': 'Zoltpy.md'
      - 'zoltr (R)': 'Zoltr.md'
      - 'RESTful API': 'Api.md'
  - Additional Information:
    - 'Getting Help': 'Help.md'
    - 'Zoltar 4 Release Notes': 'ReleaseNotes4_0.md'
    - 'Zoltar 4.1 Release Notes': 'ReleaseNotes4_1.md'
    - 'Zoltar 4.2 Release Notes': 'ReleaseNotes4_2.md'
    - 'Zoltar 4.3 Release Notes': 'ReleaseNotes4_3.md'
    - 'Zoltar 4.4 Release Notes': 'ReleaseNotes4_4.md'
