site_name: Zoltar Documentation

nav:
  - Home: 'index.md'
  - Web Tour:
      - 'Introduction': 'WebTourIntro.md'
      - 'Zoltar Home page': 'HomePage.md'
      - 'Project detail page': 'ProjectDetailPage.md'
      - 'Model detail page': 'ModelDetailPage.md'
      - 'Forecast detail page': 'ForecastDetailPage.md'
  - User Guide:
      - 'Introduction': 'UserIntro.md'
      - 'Projects': 'Projects.md'
      - 'Models': 'Models.md'
      - 'Forecasts': 'Forecasts.md'
      - 'Scores': 'Scoring.md'
      - 'Visualiations': 'Visualization.md'
      - 'Truth': 'Truth.md'
      - 'Accounts': 'Accounts.md'
  - Reference:
      - 'Concepts': 'Concepts.md'
      - 'Data model': 'DataModel.md'
      - 'File Formats': 'FileFormats.md'
      - 'Query Format': 'QueryFormat.md'
      - 'Targets': 'Targets.md'
      - 'Validation': 'Validation.md'
  - Programming libraries and API:
      - 'Introduction': 'ApiIntro.md'
      - 'zoltpy (Python)': 'Zoltpy.md'
      - 'zoltr (R)': 'Zoltr.md'
      - 'RESTful API': 'Api.md'

theme: material

markdown_extensions:
    - toc:
          permalink: true
    - tables
