site_name: Zoltar Documentation

nav:
  - Home: 'index.md'
  - Web Tour:
      - 'Introduction': 'WebTourIntro.md'
      - 'Zoltar Home page': 'HomePage.md'
      - 'Project detail page': 'ProjectDetailPage.md'
      - 'Model detail page': 'ModelDetailPage.md'
      - 'Forecast detail page': 'ForecastDetailPage.md'
  - User Guide:
      - 'Introduction': 'UserIntro.md'
      - 'Create, edit, or delete a project': 'Projects.md'
      - 'Create or delete a model': 'Models.md'
      - 'Upload, download, or delete a forecast': 'Forecasts.md'
      - 'View or download scores': 'Scoring.md'
      - 'Visualize data': 'Visualization.md'
      - 'Upload, view, download or delete truth': 'Truth.md'
      - 'Create or manage an account': 'Accounts.md'
  - Reference:
      - 'Concepts': 'Concepts.md'
      - 'Targets': 'Targets.md'
      - 'Data model': 'DataModel.md'
      - 'Validation': 'Validation.md'
      - 'File Formats': 'FileFormats.md'
  - Programming libraries and API:
      - 'zoltpy (Python)': 'Zoltpy.md'
      - 'zoltpr (R)': 'Zoltr.md'
      - 'RESTful API': 'Api.md'

theme: material
